usenameties1 = <authorliststr>, \enquote{<title>} (<year>).

options.use_name_ties = True             ## whether to use ties ('~') instead of spaces to glue together initials.
options.french_initials = False          ## whether to use French initials (i.e. Jean-Paul -> J.-P. and not J., also Philippe -> Ph. not P.)
options.force_sentence_case = False      ## Whether to reduce all but the first letter (and brace-protected letters) to lower case

