force_sentence_case = <authorliststr>, \enquote{<title>} (<year>).

options.french_initials = False          ## whether to use French initials (i.e. Jean-Paul -> J.-P. and not J., also Philippe -> Ph. not P.)
options.force_sentence_case = True       ## Whether to reduce all but the first letter (and brace-protected letters) to lower case
options.use_name_ties = False            ## whether to use ties ('~') instead of spaces to glue together initials.
options.period_after_initial = True      ## whether to add a '.' after a person's initials.
options.terse_inits = False              ## whether to format initials as, for example, "DE" rather than "D. E."
