TEMPLATES:
glossary = <description>
symbol = <description>
acronym = <description>

OPTIONS:
citation_sort = citekey                 ## order the reference list by "citekey" or "citenum" (or "nyt" etc.)
citation_label = name                   ## the type of label to use for the reference list items
case_sensitive_field_names = True       ## whether to allow field names to be case sensitive (i.e. "BOOK" will not be the same entrytype as "book")

VARIABLES:

DEFINITIONS:
