TEMPLATES:
article = \textbf{<au>:} \enquote{<title>}, in: \textit{<journal>} \textbf{<volume>} (<year>), <issue> [S.~<startpage>--<endpage>|S.~<startpage>|<eid>|] (<year>).[ <note>]
book = [\textbf{<au>:}|\textbf{<ed>} (Ed.) \textbf{:}|<organization>|<institution>|], \textit{<title>}[, <edition>~Aufl.][, (<series>; <number>)][, <address>] u.a.: <publisher> <year>.[ <note>]
inbook = \textbf{<au>:} \enquote{<title>}, in: [<ed.upper()> (Ed.): ]\textit{<booktitle>}[\textit{: <booksubtitle>}], <location> u.a.: <publisher> <year>, [S.~<startpage>--<endpage>|S.~<eid>|].[ <note>]

SPECIAL-TEMPLATES:
citelabel = <citenum>
sortkey = <citenum>
